name: Test rsync action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test rsync action
        uses: Burnett01/rsync-deployments@v7.0.2
        with:
          switches: "-n"
          path: .
          remote_path: /tmp/rs-test
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}